# Generated by Django 4.0.3 on 2025-09-14 10:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('armsApp', '0007_final_fix_aircraft_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flights',
            name='air_craft_code',
        ),
        migrations.AddField(
            model_name='airlines',
            name='code',
            field=models.CharField(default='DEF01', max_length=5, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airlines',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='code',
            field=models.CharField(default='DEFA', max_length=5, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='airport',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='airlines',
            name='image_path',
            field=models.ImageField(blank=True, null=True, upload_to='airlines'),
        ),
        migrations.CreateModel(
            name='FlightSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('departure_time', models.TimeField(help_text='Local departure time')),
                ('arrival_time', models.TimeField(help_text='Local arrival time')),
                ('duration_minutes', models.IntegerField(help_text='Flight duration in minutes')),
                ('recurrence_pattern', models.CharField(choices=[('daily', 'Daily'), ('weekdays', 'Weekdays (Mon-Fri)'), ('weekends', 'Weekends (Sat-Sun)'), ('weekly', 'Weekly'), ('custom', 'Custom Pattern')], default='daily', max_length=20)),
                ('days_of_week', models.CharField(blank=True, help_text='Days of week as comma-separated integers (0=Mon, 6=Sun)', max_length=20)),
                ('business_class_price', models.FloatField(default=0)),
                ('economy_price', models.FloatField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('delete_flag', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armsApp.aircraft')),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='armsApp.airlines')),
                ('from_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_departures', to='armsApp.airport')),
                ('to_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_arrivals', to='armsApp.airport')),
            ],
            options={
                'verbose_name_plural': 'Flight Schedules',
            },
        ),
    ]
