# Generated by Django 4.0.3 on 2025-09-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armsApp', '0008_add_flight_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='security_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='security_question',
            field=models.CharField(blank=True, choices=[('nickname', 'What is your nickname?'), ('pet', "What is your pet's name?"), ('birthplace', 'What is your place of birth?'), ('mother_maiden', "What is your mother's maiden name?"), ('first_school', 'What was the name of your first school?'), ('first_car', 'What was your first car?'), ('childhood_friend', 'What is the name of your childhood best friend?')], max_length=50, null=True),
        ),
    ]
