# Generated by Django 4.0.3 on 2025-09-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armsApp', '0009_userprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flights',
            name='currency',
            field=models.CharField(default='INR', help_text='Currency code (INR for Indian Rupees)', max_length=3),
        ),
        migrations.AddField(
            model_name='flightschedule',
            name='currency',
            field=models.CharField(default='INR', help_text='Currency code (INR for Indian Rupees)', max_length=3),
        ),
    ]
