# Generated by Django 4.0.3 on 2025-09-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armsApp', '0010_flights_currency_flightschedule_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='middle_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
