# Generated by Django 5.2.5 on 2025-09-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("armsApp", "0011_alter_reservation_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("0", "Pending Admin Approval"),
                    ("1", "Approved by Admin"),
                    ("2", "Cancelled"),
                    ("3", "Rejected by Admin"),
                ],
                default=0,
                max_length=2,
            ),
        ),
    ]
